obstacle_range: 2.0
raytrace_range: 3.0
robot_radius: 0.34
inflation_radius: 0.5
map_type: costmap
observation_sources: laser_scan_sensor #point_cloud_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /sk/laser/scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
