local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 2.0
  transform_tolerance: 0.3 
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
